/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobiledelar;

import static automobiledelar.MyDb.con;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class AddCustomer extends javax.swing.JInternalFrame {
String mode=""; 
  
public void Customer() throws SQLException
     {
        con=MyDb.getCon();
        Statement st=con.createStatement();
        String name,mob,address,email;
        name=txtn.getText();
        mob=txtph.getText();
        address=txtadd.getText();
        email=txtemail.getText();
        String xyz="hello";
 
         
     }
    /**
     * Creates new form Addcustomer
     */
    public AddCustomer() {
        initComponents();
        fetch("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        View = new javax.swing.JButton();
        AddNew = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Export1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Search = new javax.swing.JButton();
        txtser = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtph = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        txtemail = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 51, 255));
        setBorder(null);
        setTitle("Add-Customer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);
        setOpaque(true);
        setVisible(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(null);

        View.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_View_20px.png"))); // NOI18N
        View.setText("View All");
        View.setBorder(null);
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        jPanel2.add(View);
        View.setBounds(20, 10, 100, 30);

        AddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Plus_20px.png"))); // NOI18N
        AddNew.setText("Add New");
        AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewActionPerformed(evt);
            }
        });
        jPanel2.add(AddNew);
        AddNew.setBounds(140, 10, 100, 30);

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Save_20px.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel2.add(Save);
        Save.setBounds(260, 10, 100, 30);

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Available_Updates_20px.png"))); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(Update);
        Update.setBounds(380, 10, 100, 30);

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Trash_20px.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete);
        Delete.setBounds(500, 10, 100, 30);

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Clear_Symbol_20px.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel2.add(Clear);
        Clear.setBounds(620, 10, 100, 30);

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Cancel_20px.png"))); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel2.add(Cancel);
        Cancel.setBounds(860, 10, 100, 30);

        Export1.setBackground(new java.awt.Color(255, 255, 255));
        Export1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Microsoft_Excel_20px.png"))); // NOI18N
        Export1.setText("Export");
        Export1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export1ActionPerformed(evt);
            }
        });
        jPanel2.add(Export1);
        Export1.setBounds(740, 10, 100, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jk_1.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 0, 1080, 60);

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1110, 60));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(153, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 204));
        jLabel10.setText("Add-Customer");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 40, 190, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Add_User_Male_35px_1.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 30, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled_4.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 0, 1080, 119);

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 120));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Custid", "Custname", "Phone no", "Address", "Emailid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 540, 280));

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Search_20px.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel5.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 110, 30));

        txtser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserActionPerformed(evt);
            }
        });
        jPanel5.add(txtser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 420, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Customer-Name:-");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 30));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Email-id:- ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 101, 27));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Address:-");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 24));

        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnKeyTyped(evt);
            }
        });
        jPanel3.add(txtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Phone no.:-");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 30));

        txtph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphActionPerformed(evt);
            }
        });
        txtph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphKeyTyped(evt);
            }
        });
        jPanel3.add(txtph, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 220, 30));

        txtadd.setColumns(20);
        txtadd.setRows(5);
        jScrollPane2.setViewportView(txtadd);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 220, 100));
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 220, 30));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel3.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 220, 30));

        jLabel1.setText("Customer-id :-");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 30));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 380, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
   if(mode.equals("update")){
        String id,name,mob,address,email; 
        id=txtid.getText();
        
        name=txtn.getText();
        mob=txtph.getText();
        address=txtadd.getText();
        email=txtemail.getText();
        try{
            String q="update  customer set cname='"+name+"',contactno='"+mob+"',address='"+address+"',email='"+email+"' where cid="+txtid.getText();
             Connection con=MyDb.getCon();
            int x=con.createStatement().executeUpdate(q);
            {
                JOptionPane.showMessageDialog(this, "Record Updated");
                fetch("");
                 txtid.setText("");
             txtn.setText("");
             txtph.setText("");
             txtadd.setText("");
             txtemail.setText("");  
             txtser.setText("");
                
            }
        } catch (SQLException ex) {
        Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
}  
        
        
        
        
        
         
    }//GEN-LAST:event_SaveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
try {
        int x=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        String q="select* from customer where cid="+x;
        ResultSet rs=MyDb.getCon().createStatement().executeQuery(q);
        if(rs.next())
             txtid.setText(rs.getString("cid"));
             txtn.setText(rs.getString("cname"));
             txtph.setText(rs.getString("contactno"));
             txtadd.setText(rs.getString("address"));
             txtemail.setText(rs.getString("email"));
        mode="update";
        //fetch("");
    } catch (SQLException ex) {
        Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch(IndexOutOfBoundsException e)
    {
          JOptionPane.showMessageDialog(this, "select Record");
    }        
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
try {
        int x=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        String q="delete from customer where cid="+x;
        int a=MyDb.getCon().createStatement().executeUpdate(q);
        if(a>0)
            JOptionPane.showMessageDialog(this, "Record Deleteed Successfully");
        
        fetch("");
    } catch (SQLException ex) {
        Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch(IndexOutOfBoundsException e)
    {
          JOptionPane.showMessageDialog(this, "select Record");
    }      
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
             txtid.setText("");
             txtn.setText("");
             txtph.setText("");
             txtadd.setText("");
             txtemail.setText("");  
             txtser.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed
public void fetch(String wh)
{
  String col[]={"custid","custname","phone no.","Address","Email"};
        int r=0;
        try {
        String q="select * from customer"+wh;
        Connection con=MyDb.getCon();
            ResultSet rs=con.createStatement().executeQuery(q);
        if(rs.last())
        {
            r=rs.getRow();
         
        }
           rs.beforeFirst();
        String data[][]=new String[r][5];
        for(int i=0;rs.next();i++)
        {
            data[i][0]=rs.getString("cid");
            data[i][1]=rs.getString("cname");
            data[i][2]=rs.getString("contactno");
            data[i][3]=rs.getString("address");
            data[i][4]=rs.getString("email");
            
            
            
            
           
        }
        
        jTable1.setModel(new DefaultTableModel(data, col));
        
        invalidate();
        
        } catch (SQLException ex) {
        Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }   
}
    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
      fetch("");
    }//GEN-LAST:event_ViewActionPerformed

    private void txtserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
String s=txtser.getText();
if(s.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please fill value");
        }
else
{
    fetch(" where cname like '%"+s+"%'");
}        
    }//GEN-LAST:event_SearchActionPerformed

    private void AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewActionPerformed
        String id,name,mob = null,email,add; 
       
        name=txtn.getText();
        mob=txtph.getText();
        
        email=txtemail.getText();
        add=txtadd.getText();
        if(name.isEmpty() || mob.isEmpty() || email.isEmpty() ||add.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Empty field not allow");
        }
        else if( name.matches("[a-zA-z]")){
            JOptionPane.showMessageDialog(this, "Invalid Name of customer");
        }
        else if(mob.length()!= 10 || !mob.matches("[0-9]+")){
            JOptionPane.showMessageDialog(this, "Invalid phone number of customer");
        }
        
        else if( !email.matches("^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$")){
             JOptionPane.showMessageDialog(this, "Invalid email-id ");
        }
        else{
        try{
           
            String q="insert into customer(cname,contactno,address,email) values('"+name+"','"+mob+"','"+add+"','"+email+"')";
             Connection con=MyDb.getCon();
            int x=con.createStatement().executeUpdate(q);
            {
                JOptionPane.showMessageDialog(this, "Record added");
                 txtn.setText("");
             txtph.setText("");
             txtadd.setText("");
             txtemail.setText("");  
             txtser.setText("");
             fetch("");
                
            }
                    
        } catch (SQLException ex) {
        Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
        }
    }//GEN-LAST:event_AddNewActionPerformed

    private void txtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyTyped
    /*char c=evt.getKeyChar();
      if(Character.isDigit(c) ||(c==KeyEvent.VK_DELETE)) {
          txtn.setText("");
        JOptionPane.showMessageDialog(this, "Enter only Character");
        
      } 
      else{
         
      }
*/
    }//GEN-LAST:event_txtnKeyTyped

    private void txtphKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphKeyTyped
 /*char c=evt.getKeyChar();
      if(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE)) {
        
      } 
      else{
         JOptionPane.showMessageDialog(this, "Enter only Number");
      }*/        // TODO add your handling code here:
    }//GEN-LAST:event_txtphKeyTyped

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void Export1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export1ActionPerformed

        Date now = new Date();

        //DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        //Date date = new Date();
        Date date = Calendar.getInstance().getTime();
        //DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String strDate = dateFormat.format(date);
        System.out.println("Converted String: " + strDate);
        //System.out.println(dateFormat.format(date));

        Excelexport e=new Excelexport();
        try {
            System.err.println("H:\\Export\\Customer "+strDate+".xls");
            e.toExcel(jTable1, new File("H:\\Export\\Customer "+strDate+".xls"));

        } catch (IOException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Export1ActionPerformed

public static void main(String args[])
{
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNew;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Export1;
    private javax.swing.JButton Save;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtph;
    private javax.swing.JTextField txtser;
    // End of variables declaration//GEN-END:variables

   
}
