/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobiledelar;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Attendance extends javax.swing.JInternalFrame {

    String mode = "";

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();

       fillCombo();
        fillTable();
    
}

    public void fillCombo() {
        try {
            ResultSet rs = MyDb.getCon().createStatement().executeQuery("select eid,ename from employee");
            while (rs.next()) {
                combo1.addItem(rs.getString("eid") + "-" + rs.getString("ename"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void fillTable() {
        try {
            String col[] = {"Employee Name", "Attendance", "Date"};
            ResultSet rs = MyDb.getCon().createStatement().executeQuery("select e.ename,a.attendance,a.adate from employee e ,attendance a where a.eid=e.eid and a.adate='" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()) + "'");
            int r = 1;
            if (rs.last()) {
                r = rs.getRow();
            }
            String data[][] = new String[r][3];
            rs.beforeFirst();
            for (int i = 0; rs.next(); i++) {
                data[i][0] = rs.getString("ename");
                data[i][1] = rs.getString("attendance");
                data[i][2] = rs.getString("adate");
            }
            jTable1.setModel(new DefaultTableModel(data, col));
            jTable1.invalidate();
        } catch (SQLException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        Allpresent = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 255, 204));
        jLabel17.setText("Attendance");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 190, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Add_User_Male_35px_1.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled_4.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 1280, 112));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1114, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jk_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 517, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Employee Name", "Attendance", "date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 630, 360));

        jLabel2.setText("Employee Name :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 86, 26));

        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        jPanel3.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 30));

        jLabel4.setText("Attendance :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 86, 26));

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Present", "Absent", "Leave" }));
        jPanel3.add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 30));

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Save_20px.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel3.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, 30));

        Allpresent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Checked_20px_1.png"))); // NOI18N
        Allpresent.setText("All Present");
        Allpresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllpresentActionPerformed(evt);
            }
        });
        jPanel3.add(Allpresent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 110, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, 1114, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       String name, att, date,eid="";
        
        name = combo1.getSelectedItem().toString();
        att = combo2.getSelectedItem().toString();
eid=name.substring(0, name.indexOf("-"));
// JOptionPane.showMessageDialog(this, "Record Updated"+eid);
        System.out.println(eid);
        try {
            String q = "select * from attendance where eid=" + eid + " and adate='" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()) + "'";
            if (MyDb.getCon().createStatement().executeQuery(q).next()) {
                  q = "update  attendance set attendance='" + att + "' where eid="+eid;
                Connection con = MyDb.getCon();
                int x = con.createStatement().executeUpdate(q);
                {
                    JOptionPane.showMessageDialog(this, "Record Updated");

                }
            }
            else
            {
                  String s = "insert into attendance(attendance,adate,eid) values('"+att+"','" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()) + "'," + eid + ")";
                    MyDb.getCon().createStatement().executeUpdate(s);
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
fillTable();

    }//GEN-LAST:event_SaveActionPerformed

    private void AllpresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllpresentActionPerformed
        try {
            ResultSet rs = MyDb.getCon().createStatement().executeQuery("select eid from employee");
            while (rs.next()) {
                String q = "select * from attendance where eid=" + rs.getString("eid") + " and adate='" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()) + "'";
                if (MyDb.getCon().createStatement().executeQuery(q).next()) {
                    JOptionPane.showMessageDialog(this, "Attendance already marked");
                } else {
                    String s = "insert into attendance(attendance,adate,eid) values('Present','" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()) + "'," + rs.getString("eid") + ")";
                    MyDb.getCon().createStatement().executeUpdate(s);
                }
            }
            JOptionPane.showMessageDialog(this, "Attendance Marked");
        } catch (SQLException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AllpresentActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Allpresent;
    private javax.swing.JButton Save;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
