/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobiledelar;
import java.awt.List;
import java.sql.Array;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Billing extends javax.swing.JInternalFrame {

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        fetch(" ");
         fetch1(" ");
        

    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtph = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        txtemail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textservice = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        price2 = new javax.swing.JTextField();
        textname = new javax.swing.JTextField();
        AddItem = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtft = new javax.swing.JTextField();
        txts = new javax.swing.JTextField();
        txtdis = new javax.swing.JTextField();
        txtgst = new javax.swing.JTextField();
        txtd = new javax.swing.JTextField();
        txtpaym = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtit = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(693, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1210, 980, 60));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Customer-Id:-");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 30));
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Email-id:- ");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 101, 27));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Address:-");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 24));

        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnKeyTyped(evt);
            }
        });
        jPanel9.add(txtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 170, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Phone no.:-");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 30));

        txtph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphActionPerformed(evt);
            }
        });
        txtph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphKeyTyped(evt);
            }
        });
        jPanel9.add(txtph, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 170, 30));

        txtadd.setColumns(20);
        txtadd.setRows(5);
        jScrollPane2.setViewportView(txtadd);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, 70));
        jPanel9.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 170, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Customer-Name:-");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 30));
        jPanel9.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 170, 20));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Custid", "Custname", "Phone no", "Address", "Emailid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Search))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 970, 310));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Services", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name:-");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 50, 30));

        jLabel3.setText("Services:-");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 30));

        jLabel5.setText("Quantity:-");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 30));

        jLabel6.setText("Price:-");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 40, 30));
        jPanel4.add(textservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 150, 30));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel4.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 30));

        price2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price2ActionPerformed(evt);
            }
        });
        jPanel4.add(price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, 30));

        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });
        jPanel4.add(textname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 30));

        AddItem.setText("Add");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });
        jPanel4.add(AddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 90, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "services", "Quantity", "Price"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 280));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 970, 360));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(153, 255, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setText("Sub-Total :-");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 85, 27));

        jLabel46.setText("Discount :-");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 85, 27));

        jLabel51.setText("Final Total:-");
        jPanel10.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 85, 27));

        jLabel52.setText("GST :-");
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 85, 27));
        jPanel10.add(txtft, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 160, 30));

        txts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsActionPerformed(evt);
            }
        });
        jPanel10.add(txts, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 160, 30));
        jPanel10.add(txtdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 160, 30));

        txtgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgstActionPerformed(evt);
            }
        });
        jPanel10.add(txtgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 160, 30));
        jPanel10.add(txtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 130, 30));
        jPanel10.add(txtpaym, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 130, 30));

        jLabel1.setText("Payment mode:-");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 160, 80, 30));

        jLabel4.setText("Payment date:-");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 90, 30));
        jPanel10.add(txtit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 150, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 850, -1, 340));

        jScrollPane1.setViewportView(jPanel5);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 1080, 1310));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void price2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price2ActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void txtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsActionPerformed

    private void txtgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgstActionPerformed
public void fetch(String wh)
{
  String col[]={"custid","custname","phone no.","Address","Email",};
        int r=0;
        try {
        String q="select * from customer"+wh;
        Connection con=MyDb.getCon();
            ResultSet rs=con.createStatement().executeQuery(q);
        if(rs.last())
        {
            r=rs.getRow();
         
        }
           rs.beforeFirst();
        String data[][]=new String[r][5];
        for(int i=0;rs.next();i++)
        {
            data[i][0]=rs.getString("cid");
            data[i][1]=rs.getString("cname");
            data[i][2]=rs.getString("contactno");
            data[i][3]=rs.getString("address");
            data[i][4]=rs.getString("email");
            
            
            
            
           
        }
        
        jTable1.setModel(new DefaultTableModel(data, col));
        
        invalidate();
        
        } catch (SQLException ex) {
        Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
    }  
}
public void fetch1(String whw)
{
  String col[]={"Name","servicetype","Quantity","Prices","Total"};
        int r=0,s;      
        try {
        String q="select * from billing_service"+whw;
        Connection con=MyDb.getCon();
            ResultSet rs=con.createStatement().executeQuery(q);
            
        if(rs.last())
        {
            r=rs.getRow();
  
         
        }
       
           rs.beforeFirst();
        String data[][]=new String[r][5];
        for(int i=0;rs.next();i++)
        {
            data[i][0]=rs.getString("service_name");
            data[i][1]=rs.getString("service_type");
            data[i][2]=rs.getString("quantity");
            data[i][3]=rs.getString("price");
            data[i][4]=rs.getString("total");
            
            
            
            
           
        }
        
        jTable2.setModel(new DefaultTableModel(data, col));
        
        invalidate();
        
        } catch (SQLException ex) {
        Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
    }  
}
    private void txtphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphActionPerformed

    private void txtphKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphKeyTyped
        /*char c=evt.getKeyChar();
        if(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE)) {

        }
        else{
            JOptionPane.showMessageDialog(this, "Enter only Number");
        }*/        // TODO add your handling code here:
    }//GEN-LAST:event_txtphKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
String s=jTextField1.getText();
if(s.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please fill value");
        }
else
{
    fetch(" where cname like '%"+s+"%'");
}        
            
    }//GEN-LAST:event_SearchActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
       String id,name,mob = null,email,add; 
        
        //id=txtid.getText();
        name=txtn.getText();
        mob=txtph.getText();
        email=txtemail.getText();
        add=txtadd.getText();
        if(name.isEmpty() || name.matches("[a-zA-z]")){
            JOptionPane.showMessageDialog(this, "Invalid Name of customer");
        }
        else if(mob.length()!= 10 || !mob.matches("[0-9]+")){
            JOptionPane.showMessageDialog(this, "Invalid phone number of customer");
        }
        else if( !email.matches("^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$")){
             JOptionPane.showMessageDialog(this, "Invalid email-id ");
        }
        else{
        try{
           
            String q="insert into customer(cname,contactno,address,email) values('"+name+"','"+mob+"','"+add+"','"+email+"')";
             Connection con=MyDb.getCon();
            int x=con.createStatement().executeUpdate(q);
            {
                JOptionPane.showMessageDialog(this, "Record added");
                
            }
                    
        } catch (SQLException ex) {
        Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
    }
        }
      
       String titem,cid,ti,sub_t,disc,gst,finalt,paymentm,paymentd;
       sub_t=txts.getText();
       disc=txtdis.getText();
       gst=txtgst.getText();
       finalt=txtft.getText();
       paymentm=txtpaym.getText();
       paymentd=txtd.getText();
       titem=txtit.getText();
       cid=jTextField2.getText();
       try{
           
            String q="insert into billing_payment(customer_id,total_items,sub_total,discount,gst,final_total,payment_mode,payment_date) values("+cid+","+titem+","+sub_t+","+disc+","+gst+","+finalt+",'"+paymentm+"','"+paymentd+"')";
            System.out.println(q); 
            Connection con=MyDb.getCon();
            int x=con.createStatement().executeUpdate(q);
            {
                JOptionPane.showMessageDialog(this, "Record added1");
                
            }
                    
        } catch (SQLException ex) {
        Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
    }
       
        String name1,service_t ,qual ,price;
       name1=textname.getText();
       service_t=textservice.getText();
       qual=quantity.getText();
       price=price2.getText();
       
        
        /*try{
           
            String q="insert into billing_service(service_name,service_type,quantity,price) values('"+name1+"','"+service_t+"','"+qual+"','"+price+"')";
             Connection con=MyDb.getCon();
            int k=con.createStatement().executeUpdate(q);
            {
                
                
            }
                    
        } catch (SQLException ex) {
        Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
    }*/
    }//GEN-LAST:event_SubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyTyped
    }//GEN-LAST:event_txtnKeyTyped
int s=0;
    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
        DefaultTableModel model= (DefaultTableModel) jTable2.getModel();
        
model.addRow(new Object[]{textname.getText(),textservice.getText(),quantity.getText(),price2.getText()});
       
int i=Integer.parseInt(price2.getText());
       s+=i; 
        System.out.println(""+s);
       
       

        
        
        
        /*String name1,service_t ,qual ,price;
       name1=textname.getText();
       service_t=textservice.getText();
       qual=quantity.getText();
       price=price2.getText();
       
           try{
              
            String q="insert into billing_service(service_name,service_type,quantity,price) values('"+name1+"','"+service_t+"','"+qual+"','"+price+"')";
             Connection con=MyDb.getCon();
            int k=con.createStatement().executeUpdate(q);
            {
                
                
            }
                    
        } catch (SQLException ex) {
        Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
    }   */
       

        
        
        
//        t1.setText(name);
//        System.out.println("");
//        String Services=textservice.getText();
//         t1.setText(Services);
//         String Qual=quantity.getText();
//        t1.setText(Qual);
//        String price=price2.getText();
//         t1.setText(price);
           
    }//GEN-LAST:event_AddItemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
              
            String q="TRUNCATE billing_service";
             Connection con=MyDb.getCon();
            int k=con.createStatement().executeUpdate(q);
            {
            }
                    
        } catch (SQLException ex) 
        {
    }//GEN-LAST:event_jButton4ActionPerformed
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     try {
        int x=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        String q="select* from customer where cid="+x;
        ResultSet rs=MyDb.getCon().createStatement().executeQuery(q);
        if(rs.next())
             
             txtn.setText(rs.getString("cname"));
             txtph.setText(rs.getString("contactno"));
             txtadd.setText(rs.getString("address"));
             txtemail.setText(rs.getString("email"));
        
        //fetch("");
    } catch (SQLException ex) {
        Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItem;
    private javax.swing.JButton Search;
    private javax.swing.JButton Submit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField price2;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textservice;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtd;
    private javax.swing.JTextField txtdis;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtft;
    private javax.swing.JTextField txtgst;
    private javax.swing.JTextField txtit;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtpaym;
    private javax.swing.JTextField txtph;
    private javax.swing.JTextField txts;
    // End of variables declaration//GEN-END:variables

    private int getRow(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
