/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobiledelar;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Dell
 */
public class EmpScreen extends javax.swing.JFrame {
 
    /**
     * Creates new form MainScreen1
     * 
     * @param user
     */
    public EmpScreen(String user) {
       //this.setAlwaysOnTop(true);   
        this.setResizable(false);
        this.setVisible(true);
       
        initComponents();
        this.setSize(1380,730);
        this.setLocationRelativeTo(this);
        p1.setBackground(new java.awt.Color(255, 255, 255,255));
        Bill.setVisible(false);
        
        Masmenu.setVisible(false);
        lbuser1.setText(user);
      
        
       
    }

    private EmpScreen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane()
        {
            ImageIcon Img=new ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\AutomobileDelar\\src\\Image\\6006407-audi-wallpapers.jpg");
            Image image=Img.getImage();
            Image image1=image.getScaledInstance(1320, 690, Image.SCALE_SMOOTH);

            public void paintComponent(Graphics g)
            {
                super.paintComponents(g);
                g.drawImage(image1,0,0,this);
            }
        }
        ;
        Masmenu = new javax.swing.JPanel();
        c1 = new javax.swing.JPanel();
        Customer = new javax.swing.JLabel();
        c2 = new javax.swing.JPanel();
        Dealer = new javax.swing.JLabel();
        c3 = new javax.swing.JPanel();
        sparepart = new javax.swing.JLabel();
        c4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Bill = new javax.swing.JPanel();
        v1 = new javax.swing.JPanel();
        Veh = new javax.swing.JLabel();
        v2 = new javax.swing.JPanel();
        Vehp = new javax.swing.JLabel();
        v3 = new javax.swing.JPanel();
        SpareSell = new javax.swing.JLabel();
        v4 = new javax.swing.JPanel();
        SpareP = new javax.swing.JLabel();
        v5 = new javax.swing.JPanel();
        Service = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        p11 = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        p22 = new javax.swing.JPanel();
        Mas = new javax.swing.JLabel();
        p33 = new javax.swing.JPanel();
        Transaction = new javax.swing.JLabel();
        p44 = new javax.swing.JPanel();
        picture = new javax.swing.JLabel();
        p55 = new javax.swing.JPanel();
        Feedback = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        Menubar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbuser1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        Masmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c1.setBackground(new java.awt.Color(255, 255, 255));

        Customer.setText("   Customer Details");
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout c1Layout = new javax.swing.GroupLayout(c1);
        c1.setLayout(c1Layout);
        c1Layout.setHorizontalGroup(
            c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c1Layout.createSequentialGroup()
                .addComponent(Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        c1Layout.setVerticalGroup(
            c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Customer, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Masmenu.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 30));

        c2.setBackground(new java.awt.Color(255, 255, 255));

        Dealer.setText("   Dealer Details");
        Dealer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DealerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DealerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout c2Layout = new javax.swing.GroupLayout(c2);
        c2.setLayout(c2Layout);
        c2Layout.setHorizontalGroup(
            c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c2Layout.createSequentialGroup()
                .addComponent(Dealer, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        c2Layout.setVerticalGroup(
            c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dealer, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Masmenu.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 30));

        c3.setBackground(new java.awt.Color(255, 255, 255));

        sparepart.setText("   Sparepart Details");
        sparepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sparepartMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sparepartMousePressed(evt);
            }
        });

        javax.swing.GroupLayout c3Layout = new javax.swing.GroupLayout(c3);
        c3.setLayout(c3Layout);
        c3Layout.setHorizontalGroup(
            c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c3Layout.createSequentialGroup()
                .addComponent(sparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        c3Layout.setVerticalGroup(
            c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sparepart, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Masmenu.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 30));

        c4.setBackground(new java.awt.Color(255, 255, 255));
        c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c4MousePressed(evt);
            }
        });

        jLabel17.setText("   Product Details");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });

        javax.swing.GroupLayout c4Layout = new javax.swing.GroupLayout(c4);
        c4.setLayout(c4Layout);
        c4Layout.setHorizontalGroup(
            c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(c4Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        c4Layout.setVerticalGroup(
            c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Masmenu.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 30));

        desktopPane.add(Masmenu);
        Masmenu.setBounds(10, 280, 200, 120);

        Bill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v1.setBackground(new java.awt.Color(255, 255, 255));

        Veh.setText("    Vehical Bill");
        Veh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VehMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VehMousePressed(evt);
            }
        });

        javax.swing.GroupLayout v1Layout = new javax.swing.GroupLayout(v1);
        v1.setLayout(v1Layout);
        v1Layout.setHorizontalGroup(
            v1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v1Layout.createSequentialGroup()
                .addComponent(Veh, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        v1Layout.setVerticalGroup(
            v1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Veh, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Bill.add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        v2.setBackground(new java.awt.Color(255, 255, 255));

        Vehp.setText("    Vehical Purchase Bill");
        Vehp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VehpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VehpMousePressed(evt);
            }
        });

        javax.swing.GroupLayout v2Layout = new javax.swing.GroupLayout(v2);
        v2.setLayout(v2Layout);
        v2Layout.setHorizontalGroup(
            v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v2Layout.createSequentialGroup()
                .addComponent(Vehp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        v2Layout.setVerticalGroup(
            v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vehp, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Bill.add(v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, -1));

        v3.setBackground(new java.awt.Color(255, 255, 255));

        SpareSell.setText("    Sparepart Sell Bill");
        SpareSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SpareSellMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SpareSellMousePressed(evt);
            }
        });

        javax.swing.GroupLayout v3Layout = new javax.swing.GroupLayout(v3);
        v3.setLayout(v3Layout);
        v3Layout.setHorizontalGroup(
            v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v3Layout.createSequentialGroup()
                .addComponent(SpareSell, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        v3Layout.setVerticalGroup(
            v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpareSell, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Bill.add(v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, -1));

        v4.setBackground(new java.awt.Color(255, 255, 255));

        SpareP.setText("    Sparepart Purchase Bill");
        SpareP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SparePMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SparePMousePressed(evt);
            }
        });

        javax.swing.GroupLayout v4Layout = new javax.swing.GroupLayout(v4);
        v4.setLayout(v4Layout);
        v4Layout.setHorizontalGroup(
            v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v4Layout.createSequentialGroup()
                .addComponent(SpareP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        v4Layout.setVerticalGroup(
            v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpareP, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Bill.add(v4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, -1));

        v5.setBackground(new java.awt.Color(255, 255, 255));

        Service.setText("    Service Invoice Bill");
        Service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ServiceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ServiceMousePressed(evt);
            }
        });

        javax.swing.GroupLayout v5Layout = new javax.swing.GroupLayout(v5);
        v5.setLayout(v5Layout);
        v5Layout.setHorizontalGroup(
            v5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v5Layout.createSequentialGroup()
                .addComponent(Service, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        v5Layout.setVerticalGroup(
            v5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Service, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Bill.add(v5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, -1));

        desktopPane.add(Bill);
        Bill.setBounds(10, 340, 200, 150);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setForeground(new java.awt.Color(102, 102, 102));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p11.setBackground(new java.awt.Color(204, 204, 204));
        p11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p11MouseReleased(evt);
            }
        });

        Home.setText("                                   Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout p11Layout = new javax.swing.GroupLayout(p11);
        p11.setLayout(p11Layout);
        p11Layout.setHorizontalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p11Layout.createSequentialGroup()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        p11Layout.setVerticalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        p1.add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        p22.setBackground(new java.awt.Color(255, 255, 255));
        p22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mas.setBackground(new java.awt.Color(204, 204, 204));
        Mas.setText("                                  Master");
        Mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MasMousePressed(evt);
            }
        });
        p22.add(Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        p1.add(p22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, -1));

        p33.setBackground(new java.awt.Color(255, 255, 255));
        p33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Transaction.setText("                              Transaction");
        Transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransactionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TransactionMousePressed(evt);
            }
        });
        p33.add(Transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        p1.add(p33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, -1));

        p44.setBackground(new java.awt.Color(255, 255, 255));
        p44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picture.setText("                                Pictures");
        picture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pictureMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pictureMousePressed(evt);
            }
        });
        p44.add(picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        p1.add(p44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        p55.setBackground(new java.awt.Color(255, 255, 255));
        p55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Feedback.setText("                               Feedback");
        Feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FeedbackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FeedbackMousePressed(evt);
            }
        });
        p55.add(Feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        p1.add(p55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, -1));

        jPanel3.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Automobile Dealer and Services");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 200, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText(" Welcome ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 120, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("    To...");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Management Systeam");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 150, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2.setBackground(new java.awt.Color(51, 51, 51));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menubar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/icons8_Menu_45px_1.png"))); // NOI18N
        Menubar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenubarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenubarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenubarMouseReleased(evt);
            }
        });
        p2.add(Menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/icons8_Male_User_65px.png"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        lbuser1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbuser1.setForeground(new java.awt.Color(255, 255, 255));
        lbuser1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbuser1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel5.add(lbuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 90, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Hello");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/material-design-color-red-black-abstract-vector-art.jpg"))); // NOI18N
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 250, 190));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 220));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 840, 110);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1010, 40, 40, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/icons8_Lock_40px.png"))); // NOI18N
        jLabel8.setToolTipText("Lock Software");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1270, 40, 40, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/icons8_Team_50px.png"))); // NOI18N
        jLabel9.setToolTipText("Manage Accounts");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1110, 40, 50, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_SMS_40px.png"))); // NOI18N
        jLabel10.setToolTipText("Send SMS to Customer");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1200, 40, 50, 50);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
 public void setColor(JPanel p)
{
   p.setBackground(new Color(204,204,204));
    
}
void resetColor(JPanel p1){
   p1.setBackground(new Color(51,51,51));
    
}
void desetColor(JPanel p1){
   p1.setBackground(new Color(255,255,255));
    
}
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Contact s1=new Contact();
      s1.setVisible(true);
      desktopPane.add(s1);
      Bill.setVisible(false);
      Masmenu.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        LoginForm l=new LoginForm();
        l.setBounds(50, 90, 1250, 550);
        l.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void MenubarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenubarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MenubarMouseReleased

    private void MenubarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenubarMousePressed
     // TODO add your handling code here:
    }//GEN-LAST:event_MenubarMousePressed

    private void MenubarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenubarMouseExited
       resetColor(p2);
    }//GEN-LAST:event_MenubarMouseExited

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
    setColor(p11);
    desktopPane.setVisible(true);  
    Bill.setVisible(false);
    Masmenu.setVisible(false);
    
    }//GEN-LAST:event_HomeMousePressed

    private void MasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasMousePressed
     
     setColor(p22);   
     Masmenu.setVisible(true);
     Bill.setVisible(false);
     
    }//GEN-LAST:event_MasMousePressed

    private void TransactionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionMousePressed
    setColor(p33);  
    Bill.setVisible(true);
    Masmenu.setVisible(false);
   
    
    }//GEN-LAST:event_TransactionMousePressed

    private void FeedbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackMousePressed
       setColor(p55);
        Feedback f=new Feedback();
       f.setVisible(true);
       desktopPane.add(f);
       Bill.setVisible(false);
       
        Masmenu.setVisible(false);
         
    }//GEN-LAST:event_FeedbackMousePressed

    private void VehMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehMousePressed
       setColor(v1);
        SecondHandVehicleBill s=new SecondHandVehicleBill();
        s.setVisible(true);
        desktopPane.add(s);
        Bill.setVisible(false);
    Masmenu.setVisible(false);
   
    }//GEN-LAST:event_VehMousePressed

    private void VehpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehpMousePressed
     setColor(v2);
        vehicalpurchase vp=new vehicalpurchase();
      vp.setVisible(true);
       desktopPane.add(vp);
       Bill.setVisible(false);
    Masmenu.setVisible(false);
    
    }//GEN-LAST:event_VehpMousePressed

    private void SpareSellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpareSellMousePressed
       setColor(v3);
        SpearpartsellBill s1=new SpearpartsellBill();
       s1.setVisible(true);
       desktopPane.add(s1);
       Bill.setVisible(false);
       
        Masmenu.setVisible(false);
    }//GEN-LAST:event_SpareSellMousePressed

    private void SparePMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SparePMousePressed
     setColor(v4);
        SpearpartPurchase s1=new SpearpartPurchase();
       s1.setVisible(true);
       desktopPane.add(s1); 
       Bill.setVisible(false);
        
        Masmenu.setVisible(false);
    }//GEN-LAST:event_SparePMousePressed

    private void ServiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiceMousePressed
        setColor(v5);
        ServiceInvoice s1=new ServiceInvoice();
       s1.setVisible(true);
       desktopPane.add(s1);
       Bill.setVisible(false);
       
        Masmenu.setVisible(false);
    }//GEN-LAST:event_ServiceMousePressed

    private void CustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMousePressed
       AddCustomer c1=new AddCustomer();
       c1.setVisible(true);
       desktopPane.add(c1);
        Bill.setVisible(false);
       
        Masmenu.setVisible(false);
               
    }//GEN-LAST:event_CustomerMousePressed

    private void sparepartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparepartMousePressed
        setColor(c3);
        AddSparepart c1=new AddSparepart();
       c1.setVisible(true);
       desktopPane.add(c1);
        Bill.setVisible(false);
      
        Masmenu.setVisible(false);
    }//GEN-LAST:event_sparepartMousePressed

    private void DealerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DealerMousePressed
         setColor(c2);
        AddDealers c1=new AddDealers();
       c1.setVisible(true);
       desktopPane.add(c1);
        Bill.setVisible(false);
        
        Masmenu.setVisible(false);
    }//GEN-LAST:event_DealerMousePressed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        setColor(c4);
        Product c1=new Product();
       c1.setVisible(true);
       desktopPane.add(c1);
        Bill.setVisible(false);
        
        Masmenu.setVisible(false);
    }//GEN-LAST:event_jLabel17MousePressed

    private void lbuser1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbuser1InputMethodTextChanged
      
            // TODO add your handling code here:
    }//GEN-LAST:event_lbuser1InputMethodTextChanged

    private void pictureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictureMousePressed
       setColor(p44);
        Bill.setVisible(false);
       
        Masmenu.setVisible(false);
    }//GEN-LAST:event_pictureMousePressed

    private void p11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p11MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_p11MouseReleased

    private void p11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p11MousePressed
       
    }//GEN-LAST:event_p11MousePressed

    private void MasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasMouseExited
        desetColor(p22);
    }//GEN-LAST:event_MasMouseExited

    private void TransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionMouseExited
        desetColor(p33); // TODO add your handling code here:
    }//GEN-LAST:event_TransactionMouseExited

    private void pictureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictureMouseExited
         desetColor(p44);
    }//GEN-LAST:event_pictureMouseExited

    private void FeedbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackMouseExited
 desetColor(p55);        // TODO add your handling code here:
    }//GEN-LAST:event_FeedbackMouseExited

    private void c4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4MousePressed
       setColor(c1); // TODO add your handling code here:
    }//GEN-LAST:event_c4MousePressed

    private void DealerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DealerMouseExited
        desetColor(c2);        // TODO add your handling code here:
    }//GEN-LAST:event_DealerMouseExited

    private void sparepartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparepartMouseExited
        desetColor(c3);        // TODO add your handling code here:
    }//GEN-LAST:event_sparepartMouseExited

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
      desetColor(c4);
    }//GEN-LAST:event_jLabel17MouseExited

    private void VehMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehMouseExited
       desetColor(v1); // TODO add your handling code here:
    }//GEN-LAST:event_VehMouseExited

    private void VehpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehpMouseExited
      desetColor(v2);  // TODO add your handling code here:
    }//GEN-LAST:event_VehpMouseExited

    private void SpareSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpareSellMouseExited
        desetColor(v3);// TODO add your handling code here:
    }//GEN-LAST:event_SpareSellMouseExited

    private void SparePMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SparePMouseExited
      desetColor(v4);  // TODO add your handling code here:
    }//GEN-LAST:event_SparePMouseExited

    private void ServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiceMouseExited
        desetColor(v5);// TODO add your handling code here:
    }//GEN-LAST:event_ServiceMouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       MessageSender m=new MessageSender();
       m.setVisible(true);
       desktopPane.add(m);
       Bill.setVisible(false);
       Masmenu.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bill;
    private javax.swing.JLabel Customer;
    private javax.swing.JLabel Dealer;
    private javax.swing.JLabel Feedback;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Mas;
    private javax.swing.JPanel Masmenu;
    private javax.swing.JLabel Menubar;
    private javax.swing.JLabel Service;
    private javax.swing.JLabel SpareP;
    private javax.swing.JLabel SpareSell;
    private javax.swing.JLabel Transaction;
    private javax.swing.JLabel Veh;
    private javax.swing.JLabel Vehp;
    private javax.swing.JPanel c1;
    private javax.swing.JPanel c2;
    private javax.swing.JPanel c3;
    private javax.swing.JPanel c4;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbuser1;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p22;
    private javax.swing.JPanel p33;
    private javax.swing.JPanel p44;
    private javax.swing.JPanel p55;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel sparepart;
    private javax.swing.JPanel v1;
    private javax.swing.JPanel v2;
    private javax.swing.JPanel v3;
    private javax.swing.JPanel v4;
    private javax.swing.JPanel v5;
    // End of variables declaration//GEN-END:variables

}
