/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobiledelar;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Dell
 */
public class Pictures extends javax.swing.JInternalFrame {
JLabel pic;
Timer tm;
int x=0;
String[] list={
   "C:\\Users\\Dell\\Documents\\NetBeansProjects\\Automobile\\src\\Img1\\46347hd.jpg",
    "C:\\Users\\Dell\\Documents\\NetBeansProjects\\Automobile\\src\\Img1\\BMW-Car-Bike-HD-Wallpaper.jpg",
    "C:\\Users\\Dell\\Documents\\NetBeansProjects\\Automobile\\src\\Img1\\Lamborghini Black Shadow.jpg",
    "C:\\Users\\Dell\\Documents\\NetBeansProjects\\Automobile\\src\\Img1\\bmw-suv-all-terrain-vehicle-fog-89784-Reverse.jpg",
    "C:\\Users\\Dell\\Documents\\NetBeansProjects\\Automobile\\src\\Img1\\car-in-the-shadows-wallpaper-1.jpg",
    "C:\\Users\\Dell\\Documents\\NetBeansProjects\\Automobile\\src\\Img1\\ferrari-f430-bugatti-veyron-aston-martin-vantage-maserati-grant-turismo-supercars-sunset-sea-speed - Copy - Copy.jpg",
    "C:\\Users\\Dell\\Documents\\NetBeansProjects\\Automobile\\src\\Img1\\slider_1-_1600x720.jpg"
     
};
  

     
    /**
     * Creates new form Addcustomer
     */
    public Pictures()  {
      pic=new JLabel();
        pic.setBounds(0, 0, 1110, 590);
        setImageSize(6);
        tm=new Timer(4000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
             setImageSize(x);
             x+=1;
if(x>=list.length)

    x=0;

//To change body of generated methods, choose Tools | Templates.
            }
        });
add(pic);
tm.start();
setLayout(null);
setSize(1110, 590);
getContentPane().setBackground(Color.decode("#bdb67b"));
       
        
        setVisible(true);
    try {
        setClosable(true);
        setClosed(true);
    } catch (PropertyVetoException ex) {
        Logger.getLogger(Pictures.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    
    }
    public void setImageSize(int i){
        ImageIcon icon=new ImageIcon(list[i]);
        Image img=icon.getImage();
        Image newImg=img.getScaledInstance(pic.getWidth(),pic.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon newImc=new  ImageIcon(newImg);
        pic.setIcon(newImc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbpic = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 51, 255));
        setBorder(null);
        setClosable(true);
        setTitle("Add-Customer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);
        setOpaque(true);
        setVisible(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jk_1.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 0, 1080, 60);

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1110, 60));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(153, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 204));
        jLabel10.setText("Pictures");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 40, 190, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Add_User_Male_35px_1.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 30, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled_4.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 0, 1080, 119);

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 120));
        jPanel5.add(lbpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1110, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


public static void main(String args[])
{
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pictures().setVisible(true);
            }
        });
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbpic;
    // End of variables declaration//GEN-END:variables

   

   
}
