/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobiledelar;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class SecondHandVehicleBill extends javax.swing.JInternalFrame {
String mode="";
    /**
     * Creates new form SecondHandVehicleBill
     */
    public SecondHandVehicleBill() {
       
        initComponents();
         fillCombo();
         fetch("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        View = new javax.swing.JButton();
        AddNew = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Export1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Save1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtamt = new javax.swing.JTextField();
        txtvn = new javax.swing.JTextField();
        txtvno = new javax.swing.JTextField();
        txtcn = new javax.swing.JTextField();
        txtcon = new javax.swing.JTextField();
        txtdis = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        txtt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtoc = new javax.swing.JTextField();
        txtpt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(153, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 204));
        jLabel10.setText("Vehical sell Bill");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 30, 190, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Add_User_Male_35px_1.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 20, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled_4.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 0, 1080, 90);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 87));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(null);

        View.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_View_20px.png"))); // NOI18N
        View.setText("View All");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        jPanel2.add(View);
        View.setBounds(20, 10, 100, 30);

        AddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Plus_20px.png"))); // NOI18N
        AddNew.setText("Save");
        AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewActionPerformed(evt);
            }
        });
        jPanel2.add(AddNew);
        AddNew.setBounds(140, 10, 100, 30);

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Trash_20px.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete);
        Delete.setBounds(270, 10, 100, 30);

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Clear_Symbol_20px.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel2.add(Clear);
        Clear.setBounds(390, 10, 100, 30);

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Cancel_20px.png"))); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel2.add(Cancel);
        Cancel.setBounds(640, 10, 100, 30);

        Export1.setBackground(new java.awt.Color(255, 255, 255));
        Export1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Microsoft_Excel_20px.png"))); // NOI18N
        Export1.setText("Export");
        Export1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export1ActionPerformed(evt);
            }
        });
        jPanel2.add(Export1);
        Export1.setBounds(510, 10, 110, 29);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jk_1.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 0, 1080, 60);

        Save1.setText("Save");
        Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save1ActionPerformed(evt);
            }
        });
        jPanel2.add(Save1);
        Save1.setBounds(260, 20, 100, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1130, 58));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Vehicle Name :-");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 28));

        jLabel2.setText("Vehicle No :-");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 28));

        jLabel4.setText("Date :-");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 80, 28));

        jLabel5.setText("Customer Name :-");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 28));

        jLabel11.setText("Contact No :-");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 28));

        jLabel12.setText("Payment Type :-");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 100, 28));
        jPanel3.add(txtamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 150, 30));
        jPanel3.add(txtvn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 30));
        jPanel3.add(txtvno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, 30));

        txtcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnActionPerformed(evt);
            }
        });
        jPanel3.add(txtcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, 30));
        jPanel3.add(txtcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, 30));
        jPanel3.add(txtdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 150, 30));

        jLabel13.setText("Discount :-");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 90, 28));

        jLabel14.setText("Price :-");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 28));

        jPanel18.setBackground(new java.awt.Color(204, 255, 204));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel18.setForeground(new java.awt.Color(204, 255, 204));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 153, 0));
        jLabel60.setText("Total :-");

        txtt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtt.setForeground(new java.awt.Color(255, 153, 0));
        txtt.setText("0.00");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel3.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 260, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon3/icons8_Calculator_20px.png"))); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill no.", "Vehicle name", "Vehicle No", "Date", "Customer Name", "Contact nol", "Payment Type", "Amount", "Discount", "Other Charges", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 990, 70));
        jPanel3.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 150, 30));

        jLabel16.setText("Other Charges :-");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 90, 28));
        jPanel3.add(txtoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 150, 30));

        txtpt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Paytm" }));
        jPanel3.add(txtpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1060, 320));

        jLabel1.setText("Search :-");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 28));

        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 153, 29));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void fetch(String wh)
{
  String col[]={"Billno.","Vehname","Vehno.","Date","Customer name","Contact no","Payment type","Amount","Discount","Charges","Final total"};
        int r=0;
        try {
        String q="select * from vehiclesell"+wh;
        Connection con=MyDb.getCon();
            ResultSet rs=con.createStatement().executeQuery(q);
        if(rs.last())
        {
            r=rs.getRow();
         
        }
           rs.beforeFirst();
        String data[][]=new String[r][11];
        for(int i=0;rs.next();i++)
        {
            data[i][0]=rs.getString("vsid");
            data[i][1]=rs.getString("vname");
            data[i][2]=rs.getString("vno");
            data[i][3]=rs.getString("date");
            data[i][4]=rs.getString("custn");
            data[i][5]=rs.getString("mobno");
            data[i][6]=rs.getString("payment");
            data[i][7]=rs.getString("amt");
            data[i][8]=rs.getString("discount");
            data[i][9]=rs.getString("oc");
            data[i][10]=rs.getString("total");
        }
        
        jTable1.setModel(new DefaultTableModel(data, col));
        
        invalidate();
        
        } catch (SQLException ex) {
        Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }   
}
    
    
    public void fillCombo() {
        try {
            ResultSet rs = MyDb.getCon().createStatement().executeQuery("select pid,pname from product");
            while (rs.next()) {
                combo1.addItem(rs.getString("pid") + "-" + rs.getString("pname"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        fetch("");
    }//GEN-LAST:event_ViewActionPerformed

    private void AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewActionPerformed
        String vname,vno,con1,cname,p,oc,pt,disc,date,amt,t;
        vname=txtvn.getText();
        vno=txtvno.getText();
        con1=txtcon.getText();
        cname=txtcn.getText();
        
        oc=txtoc.getText();
        pt=txtpt.getSelectedItem().toString();
        disc=txtdis.getText();
         SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        date=sdf.format(txtdate.getDate());
        amt=txtamt.getText();
        t=txtt.getText();
        try{
           
            String q="insert into vehiclesell(vname,vno,date,custn,mobno,payment,amt,discount,oc,total) values('"+vname+"','"+vno+"','"+date+"','"+cname+"','"+con1+"','"+pt+"','"+amt+"','"+disc+"','"+oc+"','"+t+"')";
             Connection con=MyDb.getCon();
            int x=con.createStatement().executeUpdate(q);
            {
                JOptionPane.showMessageDialog(this, "Record added");
                 
            }
                    
        } catch (SQLException ex) {
        Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }        
    }//GEN-LAST:event_AddNewActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
try {
        int x=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        String q="delete from vehiclesell where vsid="+x;
        int a=MyDb.getCon().createStatement().executeUpdate(q);
        if(a>0)
            JOptionPane.showMessageDialog(this, "Record Deleteed Successfully");
        
        fetch("");
    } catch (SQLException ex) {
        Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch(IndexOutOfBoundsException e)
    {
          JOptionPane.showMessageDialog(this, "select Record");
    }        
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
txtamt.setText("");
txtcn.setText("");
txtcon.setText("");
txtdis.setText("");
txtoc.setText("");
txtt.setText("");
txtvn.setText("");
txtvno.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Save1ActionPerformed

    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
 try {
        String q="select * from product where pid="+(combo1.getSelectedItem().toString()).substring(0,combo1.getSelectedItem().toString().indexOf("-"));
            Connection con=MyDb.getCon();
        ResultSet rs=con.createStatement().executeQuery(q);
        if(rs.next())
        {
        String add1=rs.getString("pname");
        txtvn.setText(add1);
        String add2=rs.getString("vehicleno");
        txtvno.setText(add2);
        
        }
    } catch (SQLException ex) {
        Logger.getLogger(Allowance.class.getName()).log(Level.SEVERE, null, ex);
    }        //         // TODO add your handling code here:
       
    }//GEN-LAST:event_combo1ItemStateChanged

    private void txtcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int s1=Integer.parseInt(txtamt.getText());
int s2=Integer.parseInt(txtdis.getText());
int s3=Integer.parseInt(txtoc.getText());
int s4=s1+s3-s2;
txtt.setText(Integer.toString(s4));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Export1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export1ActionPerformed

        Date now = new Date();

        //DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        //Date date = new Date();
        Date date = Calendar.getInstance().getTime();
        //DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String strDate = dateFormat.format(date);
        System.out.println("Converted String: " + strDate);
        //System.out.println(dateFormat.format(date));

        Excelexport e=new Excelexport();
        try {
            System.err.println("H:\\Export\\Vehicalsell Bill "+strDate+".xls");
            e.toExcel(jTable1, new File("H:\\Export\\Vehicalsell Bill "+strDate+".xls"));

        } catch (IOException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Export1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNew;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Export1;
    private javax.swing.JButton Save1;
    private javax.swing.JButton View;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtamt;
    private javax.swing.JTextField txtcn;
    private javax.swing.JTextField txtcon;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtdis;
    private javax.swing.JTextField txtoc;
    private javax.swing.JComboBox<String> txtpt;
    private javax.swing.JLabel txtt;
    private javax.swing.JTextField txtvn;
    private javax.swing.JTextField txtvno;
    // End of variables declaration//GEN-END:variables
}
